# Generated by Django 3.2.16 on 2022-11-05 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbox', '0002_auto_20221101_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='comments_tally',
            field=models.ManyToManyField(blank=True, related_name='game_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
