# Generated by Django 3.2.16 on 2022-11-05 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xbox', '0003_game_comments_tally'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='comments_tally',
        ),
        migrations.AddField(
            model_name='game',
            name='commenters_tally',
            field=models.ManyToManyField(blank=True, related_name='game_commenters', to=settings.AUTH_USER_MODEL),
        ),
    ]
